spring:
  application:
    name: springboot2
  dataSource:
    url: jdbc:postgresql://localhost:5432/animes
    username: goku
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  web:
    error:
      include-stacktrace: on_param

logging:
  level:
    org:
      hibernate:
        SQL: TRACE




